### ISSUE TITLE
How to integrate it with .nwt MVC application

### ISSUE THREAD

**Issue by AmitavaHazra** [TypingDNA/TypingDnaRecorder-JavaScript#2]
I would like to integrate this js class in .net mvc application. Please let me know if there is any reference for this.
It will be helpful on either way .

1. Let's suppose mvc application is redirecting user to login.microsoftonline.com (Azure AD) and at that time we want to use it.
2. Or, We can have a local account log in in mvc application (local SQL stored account) and we want to integrate it.

Kindly guide me with some reference.

**Comment by adrianpoacatypingdna** [comment]
Hi AmitavaHazra,

Thank you for reaching out to us. At the moment our recorder is only available in Java, IOS, Android and Javascript. We do not have an integration available for .net mvc. 

Thank you,
Adrian

**Comment by adrianpoacatypingdna** [comment]
What you can do is to integrate our javascript library to integrate it in the front end. Hope this information helps.

**Comment by AmitavaHazra** [comment]
Thanks for your time @adrianpoacatypingdna
